IMPLY-5584 retry dependency check in bash script

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -438,12 +438,42 @@ pipeline {
                         sh script: '''#!/bin/bash
                             set -o pipefail
 
-                            ${MVN} dependency-check:aggregate -pl '!integration-tests,!integration-tests-imply,!api-contract' || \
-                            { echo "The OWASP dependency check has found security vulnerabilities. Please use a newer version
+                            dependency_check() {
+                                rm -f /tmp/component-reports-failed
+                                touch /tmp/component-reports-failed
+                                ${MVN} dependency-check:aggregate -pl '!integration-tests,!integration-tests-imply,!api-contract' 2>&1 | \
+                                tee >(grep -F 'Failed to request component-reports' >> /tmp/component-reports-failed)
+                            }
+
+                            DEPENDENCY_CHECK_STATUS=0
+                            ALL_ATTEMPTS_FAILED=0
+
+                            for i in $(seq 1 10); do
+                                if dependency_check; then
+                                    echo "Dependency check succeeded"
+                                    break
+                                elif [[ $(cat /tmp/component-reports-failed) ]]; then
+                                    if [[ "${i}" = "10" ]]; then
+                                        echo "All attempts are failed"
+                                        ALL_ATTEMPTS_FAILED=1
+                                    else
+                                        echo "Sleeping 30 seconds before next attempt"
+                                        sleep 30
+                                    fi
+                                else
+                                    echo "Dependency check failed not from component-reports issue. Failing"
+                                    DEPENDENCY_CHECK_STATUS=1
+                                    break
+                                fi
+                            done
+
+                            [[ "${DEPENDENCY_CHECK_STATUS}" = "0" ]] || { echo "The OWASP dependency check has found security vulnerabilities. Please use a newer version
                             of the dependency that does not have vulnerabilities. If the analysis has false positives,
                             they can be suppressed by adding entries to owasp-dependency-check-suppressions.xml (for more
                             information, see https://jeremylong.github.io/DependencyCheck/general/suppression.html).
-                            " && false; }
+                            " && exit 1; }
+
+                            [[ "${ALL_ATTEMPTS_FAILED}" = "0" ]] || false
                         ''',
                         label: 'dependency check'
                     }
