address PR comments

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -825,6 +825,144 @@ pipeline {
                                     }
                                 }
                             }
+                            stage('build') {
+                                steps {
+                                    setupMavenSettings()
+                                    sh script:'''#!/bin/bash -eux
+                                        COMMIT_SHA=$(git rev-parse HEAD)
+                                        if [[ $(git branch origin/${BRANCH_NAME} -r --contains $COMMIT_SHA) ]]; then
+                                            UPSTREAM_COMMIT_SHA=$COMMIT_SHA
+                                        else
+                                            COMMIT_SHA=$(git rev-parse HEAD^)
+                                            if [[ $(git branch origin/${BRANCH_NAME} -r --contains $COMMIT_SHA) ]]; then
+                                                UPSTREAM_COMMIT_SHA=$COMMIT_SHA
+                                            else
+                                                echo "head branch commit SHA is not found"
+                                                exit 1
+                                            fi
+                                        fi
+
+                                        # Matching the version from pom.xml
+                                        DERBYTOOLS_VERSION="10.14.2.0"
+
+                                        # Imply includes additional hadoop libraries (e.g., hadoop-aws)
+                                        HADOOP_VERSION="2.8.5"
+
+                                        MARIADB_CONNECTOR_VERSION="2.7.3"
+
+                                        cd $WORKSPACE
+
+                                        # remove snapshot suffix from pom files
+                                        INIT_DRUID_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
+                                        DRUID_VERSION=${INIT_DRUID_VERSION%%-SNAPSHOT}
+                                        mvn versions:set -DnewVersion=$DRUID_VERSION  -DgenerateBackupPoms=false
+
+                                        current_java_version=$(java -version 2>&1 >/dev/null | grep 'version' | awk '{print $3}')
+                                        echo "Compiling Druid with current Java version set. Java version=$current_java_version"
+
+                                        mvn clean install \
+                                            -Dhadoop.compile.version="$HADOOP_VERSION" \
+                                            -Danimal.sniffer.skip=true \
+                                            -Dcheckstyle.skip=true \
+                                            -Denforcer.skip=true \
+                                            -Dforbiddenapis.skip=true \
+                                            -Djacoco.skip=true \
+                                            -Dmaven.javadoc.skip=true \
+                                            -Dpmd.skip=true \
+                                            -Dspotbugs.skip=true \
+                                            -DskipTests \
+                                            -T1C \
+                                            -Dtar \
+                                            -P${BUILD_PROFILE}
+
+                                        echo "Built Druid, version: $DRUID_VERSION"
+
+                                        # Stage Druid
+                                        export STAGING_DIR=${STAGING_BASE_DIR}/${BUILD_PROFILE}
+                                        mkdir -p "$STAGING_DIR/dist"
+                                        mkdir -p "$TMP_DIR"
+                                        tar -C "$TMP_DIR" -xzf "$WORKSPACE"/distribution/target/apache-druid-*-bin.tar.gz
+                                        mv "$TMP_DIR"/apache-druid-* "$STAGING_DIR/dist/druid"
+
+                                        # Fetch the MariaDB Client from mariadb.com
+                                        MARIADB_CONNECTOR_LOCATION="$STAGING_DIR/dist/druid/extensions/mysql-metadata-storage/mariadb-java-client-${MARIADB_CONNECTOR_VERSION}.jar"
+                                        #mkdir -p "$STAGING_DIR/dist/druid/extensions/mysql-metadata-storage"
+                                        curl -o "$MARIADB_CONNECTOR_LOCATION" --retry 10 "https://downloads.mariadb.com/Connectors/java/connector-java-${MARIADB_CONNECTOR_VERSION}/mariadb-java-client-${MARIADB_CONNECTOR_VERSION}.jar"
+
+                                        if [ "$(sha1sum "$MARIADB_CONNECTOR_LOCATION" | awk '{print $1}')" != "4a2edc05bd882ad19371d2615c2635dccf8d74f0" ]
+                                        then
+                                          echo "$MARIADB_CONNECTOR_LOCATION: checksum mismatch" >&2
+                                          exit 1
+                                        fi
+
+                                        # Add hadoop-aws
+                                        (cd "$STAGING_DIR"/dist/druid && java -classpath "lib/*" org.apache.druid.cli.Main tools pull-deps -h "org.apache.hadoop:hadoop-aws:${HADOOP_VERSION}")
+
+                                        # Add derbytools to lib
+                                        DERBYTOOLS_LOCATION="$STAGING_DIR/dist/druid/lib/derbytools-$DERBYTOOLS_VERSION.jar"
+                                        curl -Lo "$DERBYTOOLS_LOCATION" "https://search.maven.org/remotecontent?filepath=org/apache/derby/derbytools/$DERBYTOOLS_VERSION/derbytools-$DERBYTOOLS_VERSION.jar"
+
+                                        if [ "$(sha1sum "$DERBYTOOLS_LOCATION" | awk '{print $1}')" != "338d5a54b4089c80414fe0ecb3899d521da69b26" ]
+                                        then
+                                          echo "$DERBYTOOLS_LOCATION: checksum mismatch" >&2
+                                          exit 1
+                                        fi
+
+                                        # Remove unsupported open-source extensions
+                                        for extension in druid-pac4j druid-ranger-security materialized-view-maintenance materialized-view-selection; do
+                                            rm -rf "${STAGING_DIR}/dist/druid/extensions/${extension}"
+                                        done
+
+                                        # Put druid on a diet
+                                        perl - <<'EOT'
+                                        use strict;
+                                        use File::Basename;
+
+                                        my $dir = "$ENV{STAGING_DIR}/dist/druid";
+                                        chdir $dir or die "chdir $dir: $!";
+
+                                        my %jars;
+                                        for my $jar (qx!find ./lib -name '*.jar'!, qx!find ./extensions -name '*.jar'!, qx!find ./hadoop-dependencies -name '*.jar'!) {
+                                          chomp $jar;
+                                          my $jarname = basename($jar);
+                                          if (exists $jars{$jarname}) {
+                                            my $depth = $jar =~ tr !/!/! - 1;
+                                            my $dots = "";
+                                            for my $x (1..$depth) {
+                                              $dots .= "../";
+                                            }
+                                            system("ln", "-sf", "${dots}$jars{$jarname}", $jar);
+                                          } else {
+                                            $jars{$jarname} = $jar;
+                                          }
+                                        }
+                                        EOT
+
+                                        function verify_checksum() {
+                                            local file="$1"
+                                            local checksum="$2"
+                                            if [ "$(sha1sum "$file" | awk '{print $1}')" != "$checksum" ]; then
+                                                1>&2 cat << EOF
+                                                    $file has changed in the druid repo! Look at the changes and incorporate them in the
+                                                    script if needed. Then update the expected sha1 in this script. Also update the imply
+                                                    startup scripts located at https://github.com/implydata/imply-release/blob/master/imply-resources/bin/$file
+                                                EOF
+                                                exit 1
+                                            fi
+                                        }
+
+                                        verify_checksum "$STAGING_DIR/dist/druid/bin/run-druid" "$EXPECTED_SHA1_RUN_DRUID"
+                                        verify_checksum "$STAGING_DIR/dist/druid/bin/verify-java" "$EXPECTED_SHA1_VERIFY_JAVA"
+                                        verify_checksum "$STAGING_DIR/dist/druid/bin/run-zk" "$EXPECTED_SHA1_RUN_ZK"
+
+                                        tar -C $STAGING_DIR/dist -czf $WORKSPACE/${ARTIFACT_NAME}-${DRUID_VERSION}-${UPSTREAM_COMMIT_SHA:0:8}.tar.gz druid
+
+                                        echo "${DRUID_VERSION}-${UPSTREAM_COMMIT_SHA:0:8}" > $WORKSPACE/build.version
+
+                                    '''.replaceAll(/\n\s+/, "\n"),
+                                    label: 'build druid and verify'
+                                } // end of steps
+                            } // end of stage('build')
                             stage('prepare upload') {
                                 steps {
                                     setupMavenSettings()
@@ -2056,7 +2194,7 @@ pipeline {
                             }
                         }
                         stages {
-                            stage('build') {
+                            stage('populate build properties') {
                                 steps {
                                     setupMavenSettings()
                                     sh script:'''#!/bin/bash -eux
@@ -2073,14 +2211,6 @@ pipeline {
                                             fi
                                         fi
 
-                                        # Matching the version from pom.xml
-                                        DERBYTOOLS_VERSION="10.14.2.0"
-
-                                        # Imply includes additional hadoop libraries (e.g., hadoop-aws)
-                                        HADOOP_VERSION="2.8.5"
-
-                                        MARIADB_CONNECTOR_VERSION="2.7.3"
-
                                         cd $WORKSPACE
 
                                         # remove snapshot suffix from pom files
@@ -2088,113 +2218,17 @@ pipeline {
                                         DRUID_VERSION=${INIT_DRUID_VERSION%%-SNAPSHOT}
                                         mvn versions:set -DnewVersion=$DRUID_VERSION  -DgenerateBackupPoms=false
 
-                                        current_java_version=$(java -version 2>&1 >/dev/null | grep 'version' | awk '{print $3}')
-                                        echo "Compiling Druid with current Java version set. Java version=$current_java_version"
-
-                                        mvn clean install \
-                                            -Dhadoop.compile.version="$HADOOP_VERSION" \
-                                            -Danimal.sniffer.skip=true \
-                                            -Dcheckstyle.skip=true \
-                                            -Denforcer.skip=true \
-                                            -Dforbiddenapis.skip=true \
-                                            -Djacoco.skip=true \
-                                            -Dmaven.javadoc.skip=true \
-                                            -Dpmd.skip=true \
-                                            -Dspotbugs.skip=true \
-                                            -DskipTests \
-                                            -T1C \
-                                            -Dtar \
-                                            -P${BUILD_PROFILE}
-
-                                        echo "Built Druid, version: $DRUID_VERSION"
-
                                         # Stage Druid
                                         export STAGING_DIR=${STAGING_BASE_DIR}/${BUILD_PROFILE}
-                                        mkdir -p "$STAGING_DIR/dist"
-                                        mkdir -p "$TMP_DIR"
-                                        tar -C "$TMP_DIR" -xzf "$WORKSPACE"/distribution/target/apache-druid-*-bin.tar.gz
-                                        mv "$TMP_DIR"/apache-druid-* "$STAGING_DIR/dist/druid"
 
-                                        # Fetch the MariaDB Client from mariadb.com
-                                        MARIADB_CONNECTOR_LOCATION="$STAGING_DIR/dist/druid/extensions/mysql-metadata-storage/mariadb-java-client-${MARIADB_CONNECTOR_VERSION}.jar"
-                                        #mkdir -p "$STAGING_DIR/dist/druid/extensions/mysql-metadata-storage"
-                                        curl -o "$MARIADB_CONNECTOR_LOCATION" --retry 10 "https://downloads.mariadb.com/Connectors/java/connector-java-${MARIADB_CONNECTOR_VERSION}/mariadb-java-client-${MARIADB_CONNECTOR_VERSION}.jar"
-
-                                        if [ "$(sha1sum "$MARIADB_CONNECTOR_LOCATION" | awk '{print $1}')" != "4a2edc05bd882ad19371d2615c2635dccf8d74f0" ]
-                                        then
-                                          echo "$MARIADB_CONNECTOR_LOCATION: checksum mismatch" >&2
-                                          exit 1
-                                        fi
-
-                                        # Add hadoop-aws
-                                        (cd "$STAGING_DIR"/dist/druid && java -classpath "lib/*" org.apache.druid.cli.Main tools pull-deps -h "org.apache.hadoop:hadoop-aws:${HADOOP_VERSION}")
-
-                                        # Add derbytools to lib
-                                        DERBYTOOLS_LOCATION="$STAGING_DIR/dist/druid/lib/derbytools-$DERBYTOOLS_VERSION.jar"
-                                        curl -Lo "$DERBYTOOLS_LOCATION" "https://search.maven.org/remotecontent?filepath=org/apache/derby/derbytools/$DERBYTOOLS_VERSION/derbytools-$DERBYTOOLS_VERSION.jar"
-
-                                        if [ "$(sha1sum "$DERBYTOOLS_LOCATION" | awk '{print $1}')" != "338d5a54b4089c80414fe0ecb3899d521da69b26" ]
-                                        then
-                                          echo "$DERBYTOOLS_LOCATION: checksum mismatch" >&2
-                                          exit 1
-                                        fi
-
-                                        # Remove unsupported open-source extensions
-                                        for extension in druid-pac4j druid-ranger-security materialized-view-maintenance materialized-view-selection; do
-                                            rm -rf "${STAGING_DIR}/dist/druid/extensions/${extension}"
-                                        done
-
-                                        # Put druid on a diet
-                                        perl - <<'EOT'
-                                        use strict;
-                                        use File::Basename;
-
-                                        my $dir = "$ENV{STAGING_DIR}/dist/druid";
-                                        chdir $dir or die "chdir $dir: $!";
-
-                                        my %jars;
-                                        for my $jar (qx!find ./lib -name '*.jar'!, qx!find ./extensions -name '*.jar'!, qx!find ./hadoop-dependencies -name '*.jar'!) {
-                                          chomp $jar;
-                                          my $jarname = basename($jar);
-                                          if (exists $jars{$jarname}) {
-                                            my $depth = $jar =~ tr !/!/! - 1;
-                                            my $dots = "";
-                                            for my $x (1..$depth) {
-                                              $dots .= "../";
-                                            }
-                                            system("ln", "-sf", "${dots}$jars{$jarname}", $jar);
-                                          } else {
-                                            $jars{$jarname} = $jar;
-                                          }
-                                        }
-                                        EOT
-
-                                        function verify_checksum() {
-                                            local file="$1"
-                                            local checksum="$2"
-                                            if [ "$(sha1sum "$file" | awk '{print $1}')" != "$checksum" ]; then
-                                                1>&2 cat << EOF
-                                                    $file has changed in the druid repo! Look at the changes and incorporate them in the
-                                                    script if needed. Then update the expected sha1 in this script. Also update the imply
-                                                    startup scripts located at https://github.com/implydata/imply-release/blob/master/imply-resources/bin/$file
-                                                EOF
-                                                exit 1
-                                            fi
-                                        }
-
-                                        verify_checksum "$STAGING_DIR/dist/druid/bin/run-druid" "$EXPECTED_SHA1_RUN_DRUID"
-                                        verify_checksum "$STAGING_DIR/dist/druid/bin/verify-java" "$EXPECTED_SHA1_VERIFY_JAVA"
-                                        verify_checksum "$STAGING_DIR/dist/druid/bin/run-zk" "$EXPECTED_SHA1_RUN_ZK"
-
-                                        tar -C $STAGING_DIR/dist -czf $WORKSPACE/${ARTIFACT_NAME}-${DRUID_VERSION}-${UPSTREAM_COMMIT_SHA:0:8}.tar.gz druid
 
                                         echo "${DRUID_VERSION}-${UPSTREAM_COMMIT_SHA:0:8}" > $WORKSPACE/build.version
 
                                     '''.replaceAll(/\n\s+/, "\n"),
                                     label: 'build druid and verify'
                                 } // end of steps
-                            } // end of stage('build')
-                            stage('upload') {
+                            } // end of stage('Populate build properties')
+                            stage('Set jenkins-verified property') {
                                 steps {
                                     script {
                                         def release_version = "None"
@@ -2231,7 +2265,7 @@ pipeline {
                                         )
                                     }
                                 }
-                            } // end of stage('upload')
+                            } // end of stage('Set jenkins-verified property')
                         } // end of stages
                         post {
                             cleanup {
@@ -2241,7 +2275,7 @@ pipeline {
                     } // end of stage('profile build and upload')
                 } // end of stages
             } // end of matrix
-        } // end of stage("Build and publish")
+        } // end of stage("Tag verified builds")
     } // end of stages
     post {
         failure {
